/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'contact-submissions': ContactSubmission;
    services: Service;
    projects: Project;
    'project-categories': ProjectCategory;
    posts: Post;
    'post-categories': PostCategory;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'bg') | ('en' | 'bg')[];
  globals: {
    site: Site;
    home: Home;
    about: About;
    privacy: Privacy;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
  };
  locale: 'en' | 'bg';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Requests submitted from the website contact forms
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  status: 'new' | 'in-progress' | 'done' | 'spam';
  firstName: string;
  lastName?: string | null;
  email: string;
  phone: string;
  message: string;
  attachments?: (number | Media)[] | null;
  source?: string | null;
  page?: string | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Service cards on the home / services pages and the service detail pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * URL of the detail page: /services/<slug>
   */
  slug: string;
  slugLock?: boolean | null;
  image?: (number | null) | Media;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The accent part is rendered in the green brand color
   */
  heroTitle: {
    before?: string | null;
    accent: string;
    after?: string | null;
  };
  heroImage?: (number | null) | Media;
  overviewHeading: string;
  /**
   * Overview paragraphs (blank line = new paragraph). The first paragraph is also used as the SEO description
   */
  overview: string;
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        industry: string;
        applications?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Case studies listed on the portfolio page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * URL of the case page: /portfolio/<slug>
   */
  slug: string;
  slugLock?: boolean | null;
  category: number | ProjectCategory;
  description: string;
  image?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories of portfolio cases — also shown as filters on the portfolio page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  _order?: string | null;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles listed on the blog page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL of the article: /blog/<slug>
   */
  slug: string;
  slugLock?: boolean | null;
  category: number | PostCategory;
  date: string;
  /**
   * Public article view counter. Updated automatically when visitors open the article page.
   */
  views?: number | null;
  description: string;
  image?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  /**
   * Quote blocks are rendered as the green gradient banner on the site
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories of blog posts — also shown as filters on the blog page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  _order?: string | null;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  status?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  attachments?: T;
  source?: T;
  page?: T;
  userAgent?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  image?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroTitle?:
    | T
    | {
        before?: T;
        accent?: T;
        after?: T;
      };
  heroImage?: T;
  overviewHeading?: T;
  overview?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        industry?: T;
        applications?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  category?: T;
  description?: T;
  image?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  category?: T;
  date?: T;
  views?: T;
  description?: T;
  image?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, contact details and footer — shared by every page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  brand: {
    name: string;
    tagline: string;
  };
  contacts: {
    phone: string;
    email: string;
    address: string;
  };
  footer: {
    tagline: string;
    copyright: string;
    mapImage?: (number | null) | Media;
  };
  /**
   * Meta tags of the listing pages that have no own content page
   */
  pagesSeo?: {
    /**
     * Leave empty to use automatically generated values
     */
    services?: {
      title?: string | null;
      description?: string | null;
    };
    /**
     * Leave empty to use automatically generated values
     */
    portfolio?: {
      title?: string | null;
      description?: string | null;
    };
    /**
     * Leave empty to use automatically generated values
     */
    blog?: {
      title?: string | null;
      description?: string | null;
    };
    /**
     * Leave empty to use automatically generated values
     */
    contact?: {
      title?: string | null;
      description?: string | null;
    };
  };
  socials?:
    | {
        label: string;
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * The accent part is rendered in the green brand color
     */
    title: {
      before?: string | null;
      accent: string;
      after?: string | null;
    };
    description: string;
    backgroundImage?: (number | null) | Media;
  };
  whyChoose: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    projectsCard: {
      eyebrow: string;
      metric: string;
      description: string;
    };
    turnaroundCard: {
      title: string;
      description: string;
    };
    trustedCard: {
      eyebrow: string;
      metric: string;
      rating: string;
      description: string;
    };
  };
  /**
   * Service cards are managed in the Services collection
   */
  services: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
  };
  process: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    steps?:
      | {
          title: string;
          /**
           * Optional shorter title used on small screens
           */
          mobileTitle?: string | null;
          description: string;
          image?: (number | null) | Media;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  projects: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    featured?: {
      /**
       * Portfolio case shown as the large featured card
       */
      project?: (number | null) | Project;
      image?: (number | null) | Media;
    };
    cta: {
      title: string;
      description: string;
    };
  };
  testimonials: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    badge: string;
    /**
     * Reviews shown in the slider on the right side
     */
    items?:
      | {
          quote: string;
          author: string;
          role: string;
          id?: string | null;
        }[]
      | null;
  };
  quoteBanner: {
    title: string;
  };
  faq: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * The accent part is rendered in the green brand color
     */
    title: {
      before?: string | null;
      accent: string;
      after?: string | null;
    };
    description: string;
    image?: (number | null) | Media;
  };
  story: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    image?: (number | null) | Media;
    storyText: string;
  };
  techPartners: {
    heading: {
      /**
       * Small label rendered as // Eyebrow //
       */
      eyebrow: string;
      /**
       * The accent part is rendered in the green brand color
       */
      title: {
        before?: string | null;
        accent: string;
        after?: string | null;
      };
    };
    partners?:
      | {
          name: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  /**
   * Shown under the title as "Last updated: …"
   */
  lastUpdated: string;
  sections?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to use automatically generated values
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        tagline?: T;
      };
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        copyright?: T;
        mapImage?: T;
      };
  pagesSeo?:
    | T
    | {
        services?:
          | T
          | {
              title?: T;
              description?: T;
            };
        portfolio?:
          | T
          | {
              title?: T;
              description?: T;
            };
        blog?:
          | T
          | {
              title?: T;
              description?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?:
          | T
          | {
              before?: T;
              accent?: T;
              after?: T;
            };
        description?: T;
        backgroundImage?: T;
      };
  whyChoose?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        projectsCard?:
          | T
          | {
              eyebrow?: T;
              metric?: T;
              description?: T;
            };
        turnaroundCard?:
          | T
          | {
              title?: T;
              description?: T;
            };
        trustedCard?:
          | T
          | {
              eyebrow?: T;
              metric?: T;
              rating?: T;
              description?: T;
            };
      };
  services?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
      };
  process?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        steps?:
          | T
          | {
              title?: T;
              mobileTitle?: T;
              description?: T;
              image?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  projects?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        featured?:
          | T
          | {
              project?: T;
              image?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  testimonials?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        badge?: T;
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              id?: T;
            };
      };
  quoteBanner?:
    | T
    | {
        title?: T;
      };
  faq?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?:
          | T
          | {
              before?: T;
              accent?: T;
              after?: T;
            };
        description?: T;
        image?: T;
      };
  story?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        image?: T;
        storyText?: T;
      };
  techPartners?:
    | T
    | {
        heading?:
          | T
          | {
              eyebrow?: T;
              title?:
                | T
                | {
                    before?: T;
                    accent?: T;
                    after?: T;
                  };
            };
        partners?:
          | T
          | {
              name?: T;
              image?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  lastUpdated?: T;
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}